### ISSUE TITLE
Add LBT support to config files

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/gateway-conf#17]
Taking as example:
https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/global_conf.json#L5-L15

Should we also add this to all/some of our configs?

**Comment by htdvisser** [comment]
Only where LBT is required, like in AS: https://github.com/TheThingsNetwork/gateway-conf/blob/master/AS1-global_conf.json#L8-L22
