### ISSUE TITLE
Provide template like config for use with poly forwarder

### ISSUE THREAD

**Issue by kersing** [TheThingsNetwork/gateway-conf#2]
For those running the poly forwarder it would be nice to have the information in a format that allows easy automatic merging with existing configuration on embedded Linux systems (basic *nix tools like sed/awk, no json parsers)

**Comment by johanstokking** [comment]
Do you have a proposal for this?

**Comment by tftelkamp** [comment]
Is it possible to add and/or overwrite specific (poly forwarder) settings in local_conf.json, and use the configs provided here as global_conf.json?

**Comment by kersing** [comment]
@tftelkamp Does not work, including 'servers;' in local_conf.json to define an additional server for poly forwarder overwrites all servers defined in global_conf.json.

**Comment by kersing** [comment]
The 'issue' has been solved with a json script for MultiTech gateways. The script is included in the poly forwarder package for MultiTech and available at https://github.com/kersing/multitech-installer (merge.js and multitech_overrides.json). Closing the issue.
