### ISSUE TITLE
CN470-510 configuration

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/gateway-conf#20]
In China, there are two bands specified: CN470-510 and CN779-787. The TX power of the latter is limited to 10 dBm, which is too low.

Therefore, we are planning a CN470-510 configuration. Most channels are reserved for China Electric, so we need to select a frequency sub band (FSB) of the channels:
- 80-87
- 88-95

We are calling for contributions on defining the channels and testing.

**Comment by RimeLink** [comment]
we have CN470-510 LoRaWAN Gateway(SX1301+SX1255) and LoRaWAN Node(SX1278).
great, we would test those frequency plan.

**Comment by martinvinnicombe** [comment]
I am in China and using a Rising gateway, its a 470mhz (SPI0 430/470/780 MHz (SX1255))

Its listening on these frequencies.. 
Centre frq khz    Bandwidth Khz
1 | 472.300     | 125 | MultiSF
1 | 472.500     | 125 | MultiSF
1 | 472.700     | 125 | MultiSF
1 | 472.900     | 125 | MultiSF
0 | 471.500     | 125 | MultiSF
0 | 471.700     | 125 | MultiSF
0 | 471.900     | 125 | MultiSF
0 | 472.100     | 125 | MultiSF
1 | 472.400     | 250 | SF7
1 | 472.900     | 125 | FSK

**Comment by htdvisser** [comment]
According to the information we have, those channels are reserved for China Electric Power, so we can only use them in areas where  China Electric Power is not operating. Therefore I think it would be a better idea to come up with a channel plan that does not overlap with them.

Additionally, in the CN470-510 band, the SF7BW250 and FSK data rates are not specified by the LoRaWAN specification, so we should not use those.

See also https://docs.google.com/spreadsheets/d/1yLx6w2kszbt6o292EruE6PwOdVs0wvCF7bsa_DN_Blc/edit?usp=sharing

**Comment by martinvinnicombe** [comment]
I don’t think there will be a simple answer for China.. I get no traffic from China power in my city (Xiamen) so there might need to be some research across the country, I have just written to the gateway manufacturer to see if there is a list of cities/frequencies..

**Comment by htdvisser** [comment]
That would probably be very valuable information. I only based the Google Sheet above on what's in the LoRaWAN regional parameters document. Nevertheless I think it would be best to define our initial channel plan with channels that are known to **not** overlap with those of China Electric Power. That way we don't burden our communities with the responsibility of finding out which channels they can use in their area.

**Comment by martinvinnicombe** [comment]
The Official Answer.. 

Hi Martin,
470 (470-510Mhz)  in China's a free frequency bands, any city can be used in China. Gateway only supports eight channels of course, defaulting to +CH: 8; 0,471500000,DR0,DR5; 1,471700000,DR0,DR5; 2,471900000,DR0,DR5; 3,472100000,DR0,DR5; 4,472300000,DR0,DR5; 5,472500000,DR0,DR5; 6,472700000,DR0,DR5; 7,472900000,DR0,DR5;.

**Comment by htdvisser** [comment]
That is interesting, those channels don't match with the sub-band alignment in the LoRaWAN specification, so we can't follow these defaults. Also, it's interesting that they don't mention China Electric Power, as the LoRaWAN specification explicitly mentions it:

<img width="836" alt="screen shot 2017-09-07 at 10 15 48" src="https://user-images.githubusercontent.com/181308/30153074-94e18ac2-93b5-11e7-977a-62da8fca3454.png">

My proposal would be to use one of the two highest FSBs, so either

- 486.3, 486.5, 486.7, 486.9, 487.1, 487.3, 487.5, 487.7
- 487.9, 488.1, 488.3, 488.5, 488.7, 488.9, 489.1, 489.3

**Comment by martinvinnicombe** [comment]
That looks good to me, will have to reset all the nodes and the gateways but thats cool.. it will be there for a long time..

**Comment by RimeLink** [comment]
80-87 and 88-95 are nice bands for CN470-510,
those align on 8 channels as well as separate bands used by China Electric Power.
now, we are testing this 2 sub-bands based on Gateway and Node.

**Comment by RimeLink** [comment]
Today, we test the CN470-510 80-88 sub-bands:
uplink    : 486.3, 486.5, 486.7, 486.9, 487.1, 487.3, 487.5, 487.7

according to LoRaWAN specification 
downlink: 506.7, 506.9, 507.1, 507.3, 507.5, 507.7, 507.9, 508.1

but the TTN Server have NOT do the "desired" TX Freq.
we have checked the Log of Gateway, the "downlink freq" is EQUAL to "uplink freq".

**Comment by martinvinnicombe** [comment]
I will try this today if i get time. 
 486.3, 486.5, 486.7, 486.9, 487.1, 487.3, 487.5, 487.7

**Comment by htdvisser** [comment]
@RimeLink: Could you please check what the server reports under "Frequency Plan" of your gateway? You can use the `ttnctl gateways status eui-...` command for this.

**Comment by triplestudio** [comment]
Our gateway id is eui-b827ebfffea5a63c.

**Comment by htdvisser** [comment]
This gateway seems to be offline, so I can't find any information about it.

**Comment by RimeLink** [comment]
Sorry, the gateway has broken network by somebody pulled out Ethernet cable.
Now, it is working well.

**Comment by htdvisser** [comment]
I found the cause of the problem that downlink was not arriving at the correct frequency. Somehow the DNS record for `router.cn.thethings.network` pointed to a server that forced the AS_920_923 channel plan (and thus downlink logic). I updated the DNS record, please check that your gateway points to `router.cn.thethings.network` and restart the gateway. It may take some time for the DNS cache to expire, so you may have to wait a couple of hours.

**Comment by RimeLink** [comment]
Great，we have checked the Log of Gateway that "router.cn.thethings.network" emit the CORRECT downlink frequency. 
Now, the Node & Gateway communicate well on CN470-510 80-81 Sub-Bands.
We would test the "Downlink" in the future.

**Comment by RimeLink** [comment]
Great，we have checked the Log of Gateway that "router.cn.thethings.network" emit the CORRECT downlink frequency.
Now, the Node & Gateway communicate well on CN470-510 80-87 Sub-Bands.
We would test the "Downlink" in the future.

**Comment by htdvisser** [comment]
Great! If communication is fine on 80-87, we can just use those, right? Could you then submit a pull request to this repository with a file called `CN-global_conf.json` that contains the gateway configuration for these channels?

**Comment by RimeLink** [comment]
Yes, the 80-87 sub-bands work well.
we have upload the "CN-global_conf.json" many times but the GitHub have not displayed, maybe My operation or the Internet has some disturb.

**Comment by martinvinnicombe** [comment]
Are you in China at the moment ? we had problems in Xiamen last week.. so keep trying

**Comment by htdvisser** [comment]
Thanks for sending the config, @RimeLink. I made a couple of changes to make it more consistent with our other configs, and added it in #21. Please download the file and see if everything works as expected.

**Comment by drlovelove** [comment]
Why can’t we use 433Mhz instead .if you think china electric power will overlap 470Mhz ?

**Comment by htdvisser** [comment]
You can, but as the LoRa Alliance defined the 470-510 frequency band specifically for China, we as TTN follow that one.

At the moment we do not have an official 433MHz channel plan, let me know if you want to help us setting that up.
