### ISSUE TITLE
Add a mapping from country to correct frequency plan.

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/gateway-conf#6]
In the console and ttnctl, we currently give people the option to select the frequency plan they want to use.

We do not have a way to check wether or not the frequency plan used is consistent with the location of the gateway. 

For this, we'd need to have a mapping between countries and their correct/preferred frequency plan.

**Comment by htdvisser** [comment]
Maybe just create symbolic links from country code to gateway conf here?

**Comment by johanstokking** [comment]
The frequency plan really is per country (or legal territory like EU) already. US, AU and CN, plus all the LoRaWAN 1.0.2 frequency plans of South-East Asia are per country. Mapping is not necessary.

What would be interesting, on the other hand, is a mapping from a point on the map to the frequency plan that needs to be used. Let's push this to long term; this is also more a goldplating issue in the Console than something related to this repository.
