### ISSUE TITLE
Add min/max frequency to EU868

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/gateway-conf#8]
Ranging from 863 to 870

See https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/global_conf.json#L23-L25

**Comment by jpmeijers** [comment]
This seems to be already fixed:
https://github.com/TheThingsNetwork/gateway-conf/blob/master/EU-global_conf.json#L14-L15

Regarding the tx_notch_freq: is it necessary and what does it do? @tftelkamp @kersing?

**Comment by temporaryaccount** [comment]
> Regarding the tx_notch_freq: is it necessary and what does it do?

It is a band-stop filter for TX which is being passed to FPGA.

https://github.com/Lora-net/lora_gateway/blob/master/libloragw/src/loragw_fpga.c#L116
